Fixes #8 Windows Compiling General
Use stdint.h since VS 2010. Credit for this change goes to user hcoona on gihub: https://github.com/hcoona/

Fixes error in main.cpp: main.cpp:121:5: error: use of undeclared identifier 'exit' when building with ninja